# Generated by Django 6.1.1 on 2026-09-29 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_name', models.CharField(default='Nameless Mastery', max_length=100)),
                ('mastery_description', models.CharField(max_length=200)),
                ('mastery_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
