# Generated by Django 6.1.1 on 2026-09-30 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery_over_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('fk_mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mastery_over_django.mastery')),
            ],
        ),
    ]
