# Generated by Django 6.1.1 on 2026-09-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastery_over_django', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_votes',
            field=models.IntegerField(default=0),
        ),
    ]
